services:
  app:
    container_name: minara-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - app-logs:/app/logs

    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: minara_postgres
    ports:
      # because of another db running on 5432
      - "5438:5432"
    env_file:
      - .env
    volumes:
      - postgres-db:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    container_name: bullmq-redis
    image: redis:alpine
    command: redis-server --appendonly yes
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres_admin:
    image: dpage/pgadmin4:latest

    depends_on:
      - postgres

    env_file:
      - .env

    ports:
      - 5050:80

networks:
  app-network:
    driver: bridge

volumes:
  app-logs:
  postgres-db:
    driver: local
  redis-data:
    driver: local
